name: Aria2-Fast Build x64 

on:
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build arai2c.exe
      env:
        VERSION: 1.37.0
      run: |
        curl -L -o Dockerfile.mingw "https://raw.githubusercontent.com/aria2/aria2/release-$VERSION/Dockerfile.mingw"
        bash patch_dockerfile.sh
        sudo docker build --build-arg HOST=x86_64-w64-mingw32 --build-arg ARIA2_VERSION=release-$VERSION --build-arg ARIA2_REF=refs/tags/release-$VERSION -t aria2-mingw - < Dockerfile.mingw
        id=$(sudo docker create aria2-mingw)
        sudo docker cp $id:/aria2/src/aria2c.exe ./aria2c-fast_x64.exe
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: aria2c-fast_x64.exe application/vnd.microsoft.portable-executable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
